# -*- coding: utf-8 -*-
"""Predicting using the deployed model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qc_W0Ij_yY76Z1o-CzL9Cky-qI5uXk5a
"""

import requests

import json
# NOTE: you must manually set API_KEY below using information retrieved from your IBM Cloud account.
API_KEY = "IYhl2VJPcsKa1DvohrhA8BwB8Wk43ShPuQ1VzL0fPMXJ"
token_response = requests.post('https://iam.cloud.ibm.com/identity/token', data={"apikey":
 API_KEY, "grant_type": 'urn:ibm:params:oauth:grant-type:apikey'})
mltoken = token_response.json()["access_token"]

header = {'Content-Type': 'application/json', 'Authorization': 'Bearer ' + mltoken}

# NOTE: manually define and pass the array(s) of values to be scored in the next line
payload_scoring = {"input_data": [{"field": [["MinTemp", "MaxTemp", "Rainfall", "Evaporation", "Sunshine", "WindGustSpeed", "WindSpeed9am", "WindSpeed3pm", "Humidity9am", "Humidity3pm", 
                                              "Pressure9am", "Pressure3pm" ,"Cloud9am", "Cloud3pm", "Temp9am", "Temp3pm"]], 
                                             "values": [[13.4, 22.9, 0.6, 0.2, 0.4, 44.0, 20.0, 24.0, 71.0, 22.0, 1007.7, 1007.1, 8, 16.9, 21.8, 21.8]]}]}

response_scoring = requests.post('https://us-south.ml.cloud.ibm.com/ml/v4/deployments/988a35a4-5d94-4dff-81e8-0fd5e93519f4/predictions?version=2022-11-22', json=payload_scoring,
 headers={'Authorization': 'Bearer ' + mltoken})
print("Scoring response")
pred = response_scoring.json() 
print(pred)
print("Predicted value: "+ pred['predictions'][0]['values'][0][0])